spring:
  application:
    name: cloud-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.130.115.232:3306/big_data?useUnicode=true&characterEncoding=utf8
    username: develop
    password: weqCDF@179
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  profiles:
    active: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root123@localhost:9000/eureka
instance:
  prefer-ip-address: true


server:
  port: 9090